name: RCN Membership
description: Application to become a member of the Rust Commercial Network (RCN)
title: Membership Application for [INSERT COMPANY, INSTITUTION, YOUR NAME, OR OTHER ENTITY]
labels: ["membership"]
assignees: 
  - LoriLorusso
body:
  - type: markdown
    attributes:
      value: |
        The Rust Commercial Network (RCN), facilitated by the Rust Foundation, is composed of Rust Foundation Members, Rust Advocates within their companies/industry, Rust Project Members, and individuals that represent commercial companies, industries, academia, and organizations that are using Rust or looking to adopt Rust. The RCN is the umbrella network that houses the RCN’s industry consortiums, working groups, etc and their work is overseen by the RCN Steering Committee.

        The RCN is designed to be a community of industry professionals, thought leaders, and Rust Project members sharing their experiences adopting Rust and using it in production.

        Membership in the RCN is free.

        > Note that the name, email address, and any company you provide will be public since GitHub issues are public. We do not use your information for any reason other than for membership purposes.
  - type: input
    id: Name
    attributes:
      label: What is your name?
    validations:
      required: true
  - type: input
    id: Email
    attributes:
      label: What is your preferred email address?
    validations:
      required: true
  - type: dropdown
    id: representation
    attributes:
      label: Do you represent a company, the Rust Project, institution (e.g. academic), consortium, yourself or other entity?
      description: In what capacity will you be represented as a member of the RCN?
      options:
        - Company
        - Rust Project
        - Institution (Academic, etc.)
        - Consortium
        - Myself
        - Other Entity
      default: 0
    validations:
      required: true
  - type: textarea
    id: entity-name
    attributes:
      label: If you represent a company, institution, consortium, or other entity, please enter it here. If you represent the Rust Project, please enter the Rust Project team.
      description: If you are representing other than yourself, please enter it. Otherwise, type 'Individual'.
      placeholder: Type company, Rust Project Team, or entity name, or type "Individual" 
    validations:
      required: true
  - type: textarea
    id: why-interested
    attributes:
      label: Why are you interested in joining the RCN?
      description: If applicable, describe work that you are doing or planning to do in the rcn.
    validations:
      required: true
